### ISSUE TITLE
2 spaces for indentation

### ISSUE THREAD

**Issue by darlanmendonca** [luizdesign/nodejs-api-skeleton#2]
Man, como sugestão, sugiro mudar pra 2 spaces a identação, creio q seja um pattern pra node, mas n tenho ctz, me corrija se eu estiver errado

https://github.com/felixge/node-style-guide#2-spaces-for-indentation

**Comment by darlanmendonca** [comment]
e pra js em si tbm

https://standardjs.com/

**Comment by darlanmendonca** [comment]
qual pattern stas seguindo?

**Comment by luizdesign** [comment]
Normalmente uso 4 espaços, porque particularmente acho que facilita a leitura, mas essa é uma discussão constante aqui na empresa.

**Comment by darlanmendonca** [comment]
entendo, no momento é uma customizada, correto?

**Comment by darlanmendonca** [comment]
pattern customizado?

**Comment by darlanmendonca** [comment]
vndo aki o .eslint, vc sta seguindo o pattern do airbnb c exceção d duas regras, indent, e comma-dangle

**Comment by darlanmendonca** [comment]
bom por mim, indiferente, ter um .eslint falando quais patterns, já é excelente, se vc segue ele full, ou customiza partes, hj, ou amanhã, whatever, o q importa é q o desenvolvimento siga um pattern specificado, se mudar mudou e o lint acusa, ta ótimo

**Comment by darlanmendonca** [comment]
considere a respeito das exceções q aplicou, mas essa issue n se faz mais necessária

**Comment by luizdesign** [comment]
Sim, por enquanto está customizada, porém estou sim considerando utilizar o default do airbnb...
