### ISSUE TITLE
arquitetura baseada em entidades

### ISSUE THREAD

**Issue by darlanmendonca** [luizdesign/nodejs-api-skeleton#3]
outra sugestão, é desenvolver a aplicação baseada em entidades, ao invés de

```
- Api
  - Controllers
  - Routers
```

fica

```
- app (este nome é o mais comum em app's node)
  - heathcheck (o nome desta pasta é o nome da entidade, healthcheck no caso)
  - users (um exemplo d outra entidade)
```

A vantagem deste pattern, é que cada pasta de entidade tem tudo que é responsável por aquela entidade, controller, model, route, etc.
Isso facilita ao se trabalhar naquela entidade, já q se tem tudo num único e pqueno escopo (a própria pasta). Os arquivos tbm levam o nome da entidade, com um sufixo de tipo, exemplo

```
- heathcheck (pasta)
  - heathcheck.controller.js
  - heathcheck.router.js
```

e quanto as rotas, elas apenas exportam um routeador express 4, daí na index.js q é onde se instancia e configura o express, vc consegue usar os roteadores, e outros middlewares, da seguinte forma

```js
const app = require('express')()
const cors = require('cors')
const gzip = require('compression')
const healthcheck = require('./healthcheck/healthcheck.router')
const users = require('./users/users.router')

app
  .use(cors())
  .use(gzip())
  .use(heathcheck)
  .use(users)
```

**Comment by luizdesign** [comment]
Interessante! Facilita bastante para escalar...
